[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "torch>=2.1.0",
    "ninja",
    "pybind11>=2.6.0"
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build = "cp312-*"
skip = "pp* *-win32 *-manylinux_i686 *_ppc64le *_s390x"